### ISSUE TITLE
Move the tree-sitter grammar to its own repo

### ISSUE THREAD

**Issue by affanshahid** [exograph/exograph#1087]
Thoughts on moving the tree-sitter grammar (`crates/builder/grammar/grammar.js`) to its own repository? and use a git submodule to refer to it.

This would enable building a language extension for [Zed](https://zed.dev/) to support highlighting for Exograph files.

As a first step we could just copy the grammar to a repo and figure out how to integrate it later, this would enable the Zed extension.

**Comment by ramnivas** [comment]
Moving grammar to its own repo will be fine. And I agree that the first step would be to simply copy the file to (for example) the Zed extension repo and when refactor into its own repo that the Exograph core and Zed extensions can submodule in.

**Comment by affanshahid** [comment]
I have a working Zed extension here: https://github.com/affanshahid/zed-exograph (incomplete). The `grammars.exograph` section in `extension.toml` needs to point to a repository containing the grammar and other `tree-sitter generate` artifacts.
https://github.com/affanshahid/zed-exograph/blob/7a2186944f1897392781464fba68cf94bc7165f4/extension.toml#L9

If you can create a repository within the Exograph org for the grammar, I can reference it in the config.
(I can also PR the artifacts if you create an empty repo)

**Comment by ramnivas** [comment]
Awesome! I have created an empty repository: https://github.com/exograph/zed-extension

**Comment by affanshahid** [comment]
Thank you, but it should probably be called something like `tree-sitter-exograph`. Based on the [Zed docs](https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md), there need to be 2 repositories:

1. A repository containing just the tree-sitter grammar
2. A repository for the Zed extension itself. The Zed extension must reference a tree-sitter grammar repository (above) which needs to be in its own repository.

Check out the[ Prisma extension configuration](https://github.com/zed-industries/zed/blob/ace371a0d8d300d8f8101af49505d1e47b0ac131/extensions/prisma/extension.toml#L14) to see what I mean. Let me know if you want to do it differently.

**Comment by ramnivas** [comment]
Ah, I see. Created https://github.com/exograph/tree-sitter-grammar.

**Comment by affanshahid** [comment]
It seems Github doesn't allow forking empty repositories 😅. Can you add something to https://github.com/exograph/tree-sitter-grammar (maybe the LICENSE or README) so I can fork and PR.

**Comment by ramnivas** [comment]
😅 indeed!

I have added a LICENSE.md to both repos.

**Comment by affanshahid** [comment]
The grammar has been moved to a separate repo (https://github.com/exograph/tree-sitter-exograph). I've opened a PR for publishing the Zed extension: https://github.com/zed-industries/extensions/pull/791. Thanks!
