### ISSUE TITLE
Allow to keep in sync the type definitions defined inside a Deno module defined with the typescript file

### ISSUE THREAD

**Issue by sebas5384** [exograph/exograph#1108]
One way is to generate a separated file with the defined types and then inside the typescript file can be imported like with the context.

```js
import { Todo } from "../generated/TodoModule.d.ts"
```

**Comment by sebas5384** [comment]
here is a first wip version: https://github.com/sebas5384/exograph/commit/d9b016e876e1ea0e84d7586dee53a0665d0fd7a8

right not I'm struggling with the tests, I can't figure how to mock the module to test it though I could write the test for the types generator and the context types file generation functions.
I could use some help to write the `test_generates_module_definitions_correctly` test

btw I'll divide in multiple commits later

**Comment by ramnivas** [comment]
Fixed by @sebas5384 in #1140
