### ISSUE TITLE
how to use base dockerfiles / batteries included PG bindings?

### ISSUE THREAD

**Issue by geoHeil** [exograph/exograph#1282]
Hi,

```bash
exo new xx
cd xx
exo yolo
Local PostgreSQL is not available: Failed to find executable: initdb (cannot find binary path)
Docker PostgreSQL is not available: Failed to find executable: docker (cannot find binary path)
Error: Neither local PostgreSQL nor Docker is available

docker run -ti ghcr.io/exograph/cli:v0.9.9 bash 
```

on my m2 mac I fixed this via:

```
brew install postgresql@16
```

but I wonder why the generated images do not include bindings for postgres given that this is mostly one of the if not the default db to be used with exograph.

**Comment by geoHeil** [comment]
I was suspecting this - and would agree that a separate dev image would be a good addition.

**Comment by geoHeil** [comment]
Also, perhaps adding a small guide on a (local/non-cloud) docker-compose setup would be highly appreciated showcasing how to perform the compilation and serving steps.

**Comment by ramnivas** [comment]
Perfect. I will implement creating a new `dev` image and add documentation on using it (for example, mounting the local filesystem into Docker so that developers can use the host filesystem to edit their code).

**Comment by ramnivas** [comment]
PR for all-included Docker image: https://github.com/exograph/exograph/pull/1283. I will create a new release to make have it published.

**Comment by geoHeil** [comment]
That was quick! Many thanks.

I suggest adding a small refinement. The procedure to work in dev with the mapped volume & reloading is clear.

Would it be possible to add a docker example for how to have a docker build that produces the final image (multistage build first then keep the files minimal) and then create the server container?

**Comment by ramnivas** [comment]
Fixed through https://github.com/exograph/exograph/pull/1283
