### ISSUE TITLE
Emit a proper error if transpilation fails

### ISSUE THREAD

**Issue by ramnivas** [exograph/exograph#1285]
If a ts file has an error, it produces no meaningful error. Instead, it just crashes with:

```
thread 'main' panicked at crates/deno-subsystem/deno-model-builder/src/system_builder.rs:238:6:
called `Result::unwrap()` on an `Err` value: Any { .. }
```

We should replace that `unwrap` with emitting a proper error to let developers know the issue with the ts file.

**Comment by geoHeil** [comment]
I face the same for:

```
❯ RUST_BACKTRACE=full exo dev
Starting server in development mode...
Watching the current directory for changes...

Verifying new model...
thread 'main' panicked at /Users/runner/work/exograph/exograph/libs/exo-sql/src/schema/constraint.rs:92:14:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:        0x104b80514 - __mh_execute_header
   1:        0x103257488 - __mh_execute_header
   2:        0x104b4f6fc - __mh_execute_header
   3:        0x104b828f8 - __mh_execute_header
   4:        0x104b8206c - __mh_execute_header
   5:        0x104b83dbc - __mh_execute_header
   6:        0x104b82bc4 - __mh_execute_header
   7:        0x104b82b58 - __mh_execute_header
   8:        0x104b82b4c - __mh_execute_header
   9:        0x106a60cf8 - ___jit_debug_register_code
  10:        0x106a60e28 - ___jit_debug_register_code
  11:        0x106a6114c - ___jit_debug_register_code
  12:        0x1030b25e0 - __mh_execute_header
  13:        0x1030b6e2c - __mh_execute_header
  14:        0x103006014 - __mh_execute_header
  15:        0x103007814 - __mh_execute_header
  16:        0x1030eabe8 - __mh_execute_header
  17:        0x1030dfd90 - __mh_execute_header
  18:        0x1030e904c - __mh_execute_header
  19:        0x1030e1680 - __mh_execute_header
  20:        0x1030fe4a4 - __mh_execute_header
  21:        0x1030f9f50 - __mh_execute_header
  22:        0x10302e6b0 - __mh_execute_header
  23:        0x1030ff510 - __mh_execute_header
./exograph/todo-app
```

a couple of days ago it still worked - now I just deleted the state of the postgres container and restarted it  and I get this error.

However, 

```bash
exo build
EXO_INTROSPECTION=true exo-server
```

works but later:

```
2024-10-07T09:34:45.178185Z ERROR exo_sql::sql::transaction: Failed to execute query: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P01), message: "relation \"venues\" does not exist", detail: None, hint: None, position: Some(Original(13)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(1449), routine: Some("parserOpenTable") }) }
```
will fail as the relations are not created in postgres as this panic also occurs for: `exo schema migrate`

**Comment by ramnivas** [comment]
I will change these unwraps to a properly emitted error.

As for the other issues you are seeing: 
- The path is the one from the CI build. Are you building Exograph locally or the one installed from the distribution? 
- Given that it works in yolo mode, the Postgres URL may point to a non-existent or unreachable URL. Can you try to `psql $EXO_POSTGRES_URL`? If that works, try `\d+` to see if the tables have been created correctly.

**Comment by geoHeil** [comment]
- I am using the CI build / download from the default distribution
- indeed `psql $EXO_POSTGRES_URL` works
- I can also connect fine from datagrip
- When executing `\d+` NO tables are there cause `exo dev` is crashing before they are created

**Comment by geoHeil** [comment]
Perhaps https://gist.github.com/geoHeil/89f11c6f735f65f0b7306a086881e60a is useful for you - at least this is how my setup looks like this.

**Comment by geoHeil** [comment]
I fear you will not be able to reproduce - I had clean docker caches multiple times but still now it is working again fine for me. @ramnivas but better error messages would indeed really be helpful

**Comment by ramnivas** [comment]
Thanks for investigating. 

Indeed, better error messages is a high priority for us. We have did a good job for parsing and typechecking errors, but not for transpilations and similar situations.
