### ISSUE TITLE
Add version header information to exo_ir file

### ISSUE THREAD

**Issue by ramnivas** [exograph/exograph#759]
Currently, we have an assumption that the exo_ir file is build with the same version as the exo-server (i.e. they share the model definition), but as we release newer versions, we need to ensure that exo-server rejects any incompatible exo_ir files with a good error message.

Open question: how do we automate model version change (not every new release means model has changed). Model changes includes:
- Source change such that structs and enums are different
- Rust version change (which may rearrange struct fields). This may not be an issue since `bincode` serialization is likely insensitive to such change.

One possibility: SHA of the sources for model crates (this may change the model version even when not strictly required, but will be definitely safe).

**Comment by ramnivas** [comment]
Related #760

**Comment by tekul** [comment]
Implented for now with a naive check against the current package version.
