### ISSUE TITLE
`exo test` doesn't catch resolver panics

### ISSUE THREAD

**Issue by ramnivas** [exograph/exograph#842]
If there is a panic while building an exo file, `exo test` doesn't report it as an error (and just ignores tests associated with that file).

**Comment by tekul** [comment]
There errors don't seem to be a problem during building the model file (failures here are reported and the test fails), but during the test runs themselves. If there is a panic in the thread running the test, the thread dies and the result for the test will not be pushed to the results channel, meaning they are omitted.

**Comment by ramnivas** [comment]
Fixed by @tekul through #844
