### ISSUE TITLE
Extract actix server creation logic into a reusable function

### ISSUE THREAD

**Issue by tekul** [exograph/exograph#883]
Something like `pub fn mk_app(...) -> impl FnOnce(&mut ServiceConfig)` will allow the Exograph server to be easily embedded in a custom actix `main` fn.

Also add `EXO_SERVER_HOST` env variable which our server will read when deciding which host to listen on before using the default.

**Comment by ramnivas** [comment]
Fixed through https://github.com/exograph/exograph/pull/885
