### ISSUE TITLE
Support for arbitrary indexes in types

### ISSUE THREAD

**Issue by MinisculeGirraffe** [exograph/exograph#945]
Howdy. 

The most immediate comparison I can draw to this project is from AWS Amplify's [GraphQL API](https://docs.amplify.aws/cli/graphql/data-modeling/).  I have a lot of experience working with that from my job, and in a lot of ways exograph does things much better.

I wish it had the ability to configure secondary indexes on types [similar to Amplify](https://docs.amplify.aws/cli/graphql/data-modeling/#configure-a-secondary-index).

### Existing Syntax:

exograph schema:
```
type Profile {
  @pk id: Int = autoIncrement()
  username: String
  }

```
GraphQL:
```
type Query {
  profile(id: Int!): Profile!
  profiles(where: ProfileFilter, orderBy: [ProfileOrdering!], limit: Int, offset: Int): [Profile!]!
}
```

### Desired Syntax
exograph schema:
```
type Profile {
  @pk id: Int = autoIncrement()
  @unique @index username: String
}
```
GraphQL Query:
```
type Query {
  profile(id: Int!): Profile!
  profileByUsername(username: String!): Profile!
  profiles(where: ProfileFilter, orderBy: [ProfileOrdering!], limit: Int, offset: Int): [Profile!]!
}
```

**Comment by ramnivas** [comment]
@MinisculeGirraffe Thanks. That is awesome to know!

That is a good feature request, and we will work on it shortly.

**Comment by ramnivas** [comment]
Given that the [`@oneOf`](https://github.com/graphql/graphql-spec/pull/825) standardization is right around the corner, we can use it to offer this functionality by overloading the same query with different arguments.

Note: There is a separate issue of offering control over index creation (currently, we create them for all fields). We will spec that control separately.

Consider the following example:

```exo
type Person {
  ...
  @unique username: String
  @unique("email_primary") primaryEmailId: String
  @unique("email_secondary") secondaryEmailId: String
  @unique("email_primary", "email_secondary") emailDomain: String
}
```

We could offer a new query--`personBy`--to get the entity with any unique field combination.

```graphql
type Query {
  ...

  personBy(where: PersonUniqueFilter!): Person!
}

// Note the "oneOf" directive
input PersonUniqueFilter @oneOf {
  username: PersonUniqueUsernameFilter
  emailPrimary: PersonUniqueEmailPrimaryFilter
  emailSecondary: PersonUniqueEmailSecondaryFilter
}

input PersonUniqueUsernameFilter {
    username: String!
}

input PersonUniqueEmailPrimaryFilter {
    primaryEmailId: String!
    emailDomain: String!
}

input PersonUniqueEmailSecondaryFilter {
    secondaryEmailId: String!
    emailDomain: String!
}
```

Now, developers can make the following queries:

```graphql
personBy(where: {username: ""}) {
  ...
}

personBy(where: {emailPrimary: { primaryEmailId: "..", emailDomain: ".."}}) {
  ...
}

personBy(where: {emailSecondary: { secondaryEmailId: "..", emailDomain: ".."}}) {
  ...
}
```

Ideally, we would have folded this along with the base `person` query, but there isn't a way to express it with `oneOf`. The `oneArgument` directive discussed [here](https://gist.github.com/benjie/e45540ad25ce9c33c2a1552da38adb91#arguments) would have been very helpful. It would have also supported nicer queries such as `person(id: ..)` and `person(emailPrimary: { primaryEmailId: "..", emailDomain: ".."})`. However, it doesn't look like it will be standardized anytime soon.

@MinisculeGirraffe Please let us know your thoughts.

**Comment by MinisculeGirraffe** [comment]
The primary issue being as a developer I want to control which index is used in a specific scenario. This is way more important in DynamoDB because you literally can't write queries with bad access patterns. But the concept is still an issue in SQL, it's just only an issue once you have enough data for it to show up.

Indexing every field is kind of a non-starter because it's going to cause crazy write amplification that I wouldn't be comfortable using for anything serious. 

As for the API, I think `oneOf` would be the preferable method of expressing this. 

Having separate queries per index is an acceptable solution but not the ideal API to describe it.  Amplify was kind of forced into that because there's not really a better option.

**Comment by ramnivas** [comment]
@MinisculeGirraffe, I agree. I have added https://github.com/exograph/exograph/issues/950 to track the index issue.

> Having separate queries per index is an acceptable solution but not the ideal API to describe it. Amplify was kind of forced into that because there's not really a better option.

This will be only for unique field combinations to return a single entity for the specified combination. We will still have the collection query for the `people(where: ...)` form that returns a list.

**Comment by ramnivas** [comment]
PR #1005 fixes this. However, we didn't go for `oneOf` for two reasons:
- It isn't a standard yet
- It doesn't make as nicer APIs as initially thought (due to an extra level of indirection). We really need [`@oneArgument`](https://gist.github.com/benjie/e45540ad25ce9c33c2a1552da38adb91#arguments), since that allows avoiding the extra level.

**Comment by MinisculeGirraffe** [comment]
This is sweet! 

Can't wait to re-visit exograph. Amplify has been a constant source of frustration and pain for me.

The changes that have been implemented since I last investigated this really looks like you had solved every single one of my complaints about Amplify.
