### ISSUE TITLE
How to persist the token between playground reloads?

### ISSUE THREAD

**Issue by affanshahid** [exograph/exograph#997]
First of all great project guys, surprised it doesn't have way more stars. One small issue with the playground: it becomes annoying to set the token every time you open the playground during dev. I tried setting the setting "Persist headers" to true, but that gets reset with the reload too. Is this a bug or something wrong on my end?

Also, willing to PR if this is not a feature yet

**Comment by ramnivas** [comment]
Thanks!

I took a quick look, and it appears that the "Persist headers" setting itself doesn't get persisted across reloads. We will take a look shortly.

**Comment by ramnivas** [comment]
A quick update. I have a fix, but I am now running into https://github.com/graphql/graphiql/pull/3371, where if the user provides a header value, a new tab gets created on a window reload. I will continue to explore.

**Comment by ramnivas** [comment]
We also seems to running into https://github.com/graphql/graphiql/issues/1984

**Comment by ramnivas** [comment]
@affanshahid I have https://github.com/exograph/exograph/pull/999 for this. It does make a compromise as mentioned in the comment there, so please let me know what do you think.

**Comment by affanshahid** [comment]
Sounds good. Seems like a fine compromise until the underlying GraphiQL issues are resolved.

**Comment by ramnivas** [comment]
Thanks @affanshahid.
